; Listing generated by Microsoft (R) Optimizing Compiler Version 19.33.31629.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__529D0EAA_concurrencysal@h DB 01H
__7EC34687_sal@h DB 01H
__35A2D2DF_vadefs@h DB 01H
__5F022EB5_vcruntime@h DB 01H
__BBDF6BA8_xkeycheck@h DB 01H
__7F8F4960_yvals_core@h DB 01H
__F3D99286_limits@h DB 01H
__F2E1951A_climits DB 01H
__6569C2CA_corecrt@h DB 01H
__8B8B49C3_vcruntime_new@h DB 01H
__5021BF8A_vcruntime_new_debug@h DB 01H
__49916C16_crtdbg@h DB 01H
__0FF1727D_crtdefs@h DB 01H
__327B4A79_use_ansi@h DB 01H
__C04E0157_yvals@h DB 01H
__741AE07E_corecrt_math@h DB 01H
__91D68F2D_math@h DB 01H
__6C20D4D3_corecrt_malloc@h DB 01H
__C9393812_stddef@h DB 01H
__D493B9BD_corecrt_search@h DB 01H
__1473E23E_corecrt_wstdlib@h DB 01H
__B49664B7_stdlib@h DB 01H
__760EB7E8_cstdlib DB 01H
__C9757830_xtr1common DB 01H
__E5CDC221_intrin0@inl@h DB 01H
__16DCCB76_intrin0@h DB 01H
__1C794830_cmath DB 01H
__A2143F22_corecrt_stdio_config@h DB 01H
__829E1958_corecrt_wstdio@h DB 01H
__6DFAE8B8_stdio@h DB 01H
__46E22952_cstdio DB 01H
__CDDAF8CA_errno@h DB 01H
__74AC4223_vcruntime_string@h DB 01H
__1FEB9909_corecrt_memcpy_s@h DB 01H
__A751F051_corecrt_memory@h DB 01H
__9200769A_corecrt_wstring@h DB 01H
__32E5F013_string@h DB 01H
__3A9C1F08_cstring DB 01H
__C6E16F6F_corecrt_wconio@h DB 01H
__5DB64B66_corecrt_wctype@h DB 01H
__CB8D9B53_corecrt_wdirect@h DB 01H
__A9063C41_corecrt_share@h DB 01H
__6D390390_corecrt_wio@h DB 01H
__61BDDCD5_corecrt_wprocess@h DB 01H
__1157D6BA_corecrt_wtime@h DB 01H
__64F617E8_types@h DB 01H
__1DC1E279_stat@h DB 01H
__93DC0B45_wchar@h DB 01H
__DC69FF01_cwchar DB 01H
__D3C56D45_cstddef DB 01H
__485B7899_initializer_list DB 01H
__B61CA571_xstddef DB 01H
__9FA97A37_iosfwd DB 01H
__4DAFBCB9_stdint@h DB 01H
__CB505695_cstdint DB 01H
__F576AD63_type_traits DB 01H
__41033263_utility DB 01H
__2177C444_xutility DB 01H
__30DB7304_iterator DB 01H
__5B81F060_share@h DB 01H
__33989847___msvc_system_error_abi@hpp DB 01H
__DBC35DA9_cerrno DB 01H
__20BB4341_malloc@h DB 01H
__3C5D8049_corecrt_terminate@h DB 01H
__5569C08B_eh@h DB 01H
__58CFBAD8_vcruntime_exception@h DB 01H
__C7AE1CEB_exception DB 01H
__158E8E48_float@h DB 01H
__35A6E2D5_cfloat DB 01H
__A7274850_isa_availability@h DB 01H
__5340AFB1_limits DB 01H
__C7AADC23_new DB 01H
__CDA2903D_xatomic@h DB 01H
__2B9651A0_xmemory DB 01H
__5F45D73C_xstring DB 01H
__4EE026B6_stdexcept DB 01H
__3C179730_xcall_once@h DB 01H
__68DB1458_xerrc@h DB 01H
__A0B61CF9_time@h DB 01H
__DACAD438_ctime DB 01H
__97B32705_xtimec@h DB 01H
__53357DCA_xthreads@h DB 01H
__3875F373_atomic DB 01H
__834A8510_system_error DB 01H
__B3F9668E_vcruntime_typeinfo@h DB 01H
__51A8375D_typeinfo DB 01H
__EFEEA33F_memory DB 01H
__C3ABF430_xfacet DB 01H
__215922A6___msvc_xlocinfo_types@hpp DB 01H
__B2D2BA86_ctype@h DB 01H
__4929CEF5_cctype DB 01H
__A3D09DBA_locale@h DB 01H
__E5A26B39_clocale DB 01H
__4E21D495_xlocinfo DB 01H
__807BA30D_xlocale DB 01H
__77C4A386_xiosbase DB 01H
__4C409E0A_streambuf DB 01H
__1EFCC51A_xlocnum DB 01H
__3F67E635_ios DB 01H
__936B79C9_ostream DB 01H
__F0BB4CF3_istream DB 01H
__430EBE5B_iostream DB 01H
__BEC99EB2_Log@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	__JustMyCode_Default
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+41
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_K@Z DD imagerel $LN3
	DD	imagerel $LN3+46
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_K@Z DD 025051801H
	DD	01132318H
	DD	0700c001dH
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX@Z DD 025051301H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\C++Projects\Classes\Classes\src\Log.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 224
__formal$ = 232
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__BEC99EB2_Log@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\C++Projects\Classes\Classes\src\Log.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 224
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__BEC99EB2_Log@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
